language: rust
sudo: false

rust: nightly
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo fmt --all -- --write-mode=diff
  - cargo test
  - cargo bench

notifications:
  email:
    on_success: never

branches:
    except:
    - /.*(.tmp)$/

